CashBlockApp/Controllers/BodegueroController.cs
using CashBlockApp.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using CashBlockApp.Data;

namespace CashBlockApp.Controllers
{
    public class BodegueroController : Controller
    {
        private readonly CashblockContext _context;

        public BodegueroController(CashblockContext context)
        {
            _context = context;
        }

        // GET: /Bodeguero/Inventario
        [HttpGet]
        public async Task<IActionResult> Inventario()
        {
            var inventario = await _context.Existencias
                .Include(e => e.IdProductoNavigation)
                .Include(e => e.IdAlmacenNavigation)
                .Select(e => new
                {
                    CodigoProducto = e.IdProducto.ToString(),
                    NombreProducto = e.IdProductoNavigation.Nombre,

                    CantidadDisponible = e.CantidadAlmacen,

                    IdAlmacen = e.IdAlmacen,
                    UbicacionAlmacen = e.IdAlmacen.ToString(),

                    IdProducto = e.IdProducto
                })
                .OrderBy(i => i.IdAlmacen)
                .ThenBy(i => i.NombreProducto)
                .ToListAsync();

            return View(inventario);
        }

        // POST: /Bodeguero/GuardarStock
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GuardarStock(int IdProducto, int IdAlmacen, int CantidadAlmacen)
        {
            var existenciaOriginal = await _context.Existencias
                .FirstOrDefaultAsync(e => e.IdProducto == IdProducto && e.IdAlmacen == IdAlmacen);

            if (existenciaOriginal == null)
            {
                TempData["Error"] = "Error: El registro de existencia no fue encontrado.";
                return RedirectToAction(nameof(Inventario));
            }

            existenciaOriginal.CantidadAlmacen = CantidadAlmacen;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(existenciaOriginal);
                    await _context.SaveChangesAsync();
                    TempData["Success"] = $"Stock actualizado: {IdProducto} en almacén {IdAlmacen}. Nueva cantidad: {existenciaOriginal.CantidadAlmacen}";
                }
                catch (DbUpdateConcurrencyException)
                {
                    TempData["Error"] = "Error de concurrencia al actualizar el stock.";
                }
                catch (Exception ex)
                {
                    TempData["Error"] = $"Error al guardar: {ex.Message}";
                }
            }
            else
            {
                TempData["Error"] = "El valor del stock no es válido.";
            }

            return RedirectToAction(nameof(Inventario));
        }
    }
}

CashBlockApp/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CashBlockApp.Models.Entities;

namespace CashBlockApp.Controllers
{
    public class ComprasController : Controller
    {
        private readonly CashblockContext _context;

        public ComprasController(CashblockContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
            var cashblockContext = _context.Compras.Include(c => c.CedulaEmpleadoNavigation);
            return View(await cashblockContext.ToListAsync());
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .Include(c => c.CedulaEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdCompra == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado");
            return View();
        }

        // POST: Compras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCompra,PrecioTotal,FechaCompra,CedulaEmpleado")] Compra compra)
        {
            if (ModelState.IsValid)
            {
                _context.Add(compra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado", compra.CedulaEmpleado);
            return View(compra);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras.FindAsync(id);
            if (compra == null)
            {
                return NotFound();
            }
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado", compra.CedulaEmpleado);
            return View(compra);
        }

        // POST: Compras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCompra,PrecioTotal,FechaCompra,CedulaEmpleado")] Compra compra)
        {
            if (id != compra.IdCompra)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(compra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompraExists(compra.IdCompra))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado", compra.CedulaEmpleado);
            return View(compra);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var compra = await _context.Compras
                .Include(c => c.CedulaEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdCompra == id);
            if (compra == null)
            {
                return NotFound();
            }

            return View(compra);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var compra = await _context.Compras.FindAsync(id);
            if (compra != null)
            {
                _context.Compras.Remove(compra);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompraExists(int id)
        {
            return _context.Compras.Any(e => e.IdCompra == id);
        }
    }
}

CashBlockApp/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CashBlockApp.Models.Entities;

namespace CashBlockApp.Controllers
{
    public class VentasController : Controller
    {
        private readonly CashblockContext _context;

        public VentasController(CashblockContext context)
        {
            _context = context;
        }

        // GET: Ventas
        public async Task<IActionResult> Index()
        {
            var cashblockContext = _context.Venta.Include(v => v.CedulaClienteNavigation).Include(v => v.CedulaEmpleadoNavigation);
            return View(await cashblockContext.ToListAsync());
        }

        // GET: Ventas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Venta
                .Include(v => v.CedulaClienteNavigation)
                .Include(v => v.CedulaEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdVenta == id);
            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // GET: Ventas/Create
        public IActionResult Create()
        {
            ViewData["CedulaCliente"] = new SelectList(_context.Clientes, "CedulaCliente", "CedulaCliente");
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado");
            return View();
        }

        // POST: Ventas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVenta,TotalProductos,FechaVenta,PrecioTotal,CedulaEmpleado,CedulaCliente")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CedulaCliente"] = new SelectList(_context.Clientes, "CedulaCliente", "CedulaCliente", venta.CedulaCliente);
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado", venta.CedulaEmpleado);
            return View(venta);
        }

        // GET: Ventas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Venta.FindAsync(id);
            if (venta == null)
            {
                return NotFound();
            }
            ViewData["CedulaCliente"] = new SelectList(_context.Clientes, "CedulaCliente", "CedulaCliente", venta.CedulaCliente);
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado", venta.CedulaEmpleado);
            return View(venta);
        }

        // POST: Ventas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdVenta,TotalProductos,FechaVenta,PrecioTotal,CedulaEmpleado,CedulaCliente")] Venta venta)
        {
            if (id != venta.IdVenta)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VentaExists(venta.IdVenta))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CedulaCliente"] = new SelectList(_context.Clientes, "CedulaCliente", "CedulaCliente", venta.CedulaCliente);
            ViewData["CedulaEmpleado"] = new SelectList(_context.Empleados, "CedulaEmpleado", "CedulaEmpleado", venta.CedulaEmpleado);
            return View(venta);
        }

        // GET: Ventas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Venta
                .Include(v => v.CedulaClienteNavigation)
                .Include(v => v.CedulaEmpleadoNavigation)
                .FirstOrDefaultAsync(m => m.IdVenta == id);
            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venta = await _context.Venta.FindAsync(id);
            if (venta != null)
            {
                _context.Venta.Remove(venta);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VentaExists(int id)
        {
            return _context.Venta.Any(e => e.IdVenta == id);
        }
    }
}

CashBlockApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    var usuarioId = HttpContextAccessor.HttpContext.Session.GetInt32("IdUsuario");
    var perfilId = HttpContextAccessor.HttpContext.Session.GetInt32("IdPerfiles");
    var nombreUsuario = HttpContextAccessor.HttpContext.Session.GetString("NombreUsuario");
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CashBlock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CashBlockApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="../img/logotipo_cashblock.png" alt="Logo Cashblock" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (usuarioId != null)
                        {
                            @if (perfilId == 1) // Administrador
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                                        <i class="bi bi-house-door"></i> Home
                                    </a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-gear"></i> Administración
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" asp-controller="Usuarios" asp-action="Index">Usuarios</a></li>
                                        <li><a class="dropdown-item" asp-controller="Clientes" asp-action="Index">Clientes</a></li>
                                        <li><a class="dropdown-item" asp-controller="Empleados" asp-action="Index">Empleados</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" asp-controller="Productos" asp-action="Index">Productos</a></li>
                                        <li><a class="dropdown-item" asp-controller="Categorias" asp-action="Index">Categorías</a></li>
                                        <li><a class="dropdown-item" asp-controller="Proveedores" asp-action="Index">Proveedores</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" asp-controller="Ventas" asp-action="Index">Ventas</a></li>
                                        <li><a class="dropdown-item" asp-controller="Compras" asp-action="Index">Compras</a></li>
                                        <li><a class="dropdown-item" asp-controller="Usuarios" asp-action="Reporte">Reporte Usuarios</a></li>

                                    </ul>
                                </li>
                            }
                            else if (perfilId == 2) // Vendedor
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Vendedor" asp-action="Index">
                                        <i class="bi bi-speedometer2"></i> Dashboard
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Vendedor" asp-action="NuevaVenta">
                                        <i class="bi bi-cart-plus"></i> Nueva Venta
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Vendedor" asp-action="Productos">
                                        <i class="bi bi-box-seam"></i> Productos
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Vendedor" asp-action="MisVentas">
                                        <i class="bi bi-receipt"></i> Mis Ventas
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Usuarios" asp-action="Reporte">
                                        <i class="bi bi-people"></i> Reporte Usuarios
                                    </a>
                                </li>
                            }
                            else if (perfilId == 3) // Bodeguero
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Bodeguero" asp-action="Inventario">
                                        <i class="bi bi-boxes"></i> Inventario
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Existencias" asp-action="Index">
                                        <i class="bi bi-clipboard-data"></i> Existencias
                                    </a>
                                </li>
                            }
                            else if (perfilId == 4) // Cajero
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                                        <i class="bi bi-cash-register"></i> Caja
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Ventas" asp-action="Index">
                                        <i class="bi bi-receipt"></i> Ventas
                                    </a>
                                </li>
                            }
                            else if (perfilId == 5) // Cliente
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Cliente" asp-action="Index">
                                        <i class="bi bi-house-door"></i> Inicio
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Cliente" asp-action="Productos">
                                        <i class="bi bi-cart"></i> Productos
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Cliente" asp-action="MisCompras">
                                        <i class="bi bi-bag-check"></i> Mis Compras
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Cliente" asp-action="MiPerfil">
                                        <i class="bi bi-person-circle"></i> Mi Perfil
                                    </a>
                                </li>
                            }
                        }
                    </ul>

                    <!-- Usuario logueado -->
                    @if (usuarioId != null)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-person-circle"></i> @nombreUsuario
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                    <li>
                                        <span class="dropdown-item-text">
                                            <strong>Rol:</strong>
                                            @switch (perfilId)
                                            {
                                                case 1:
                                                    <span>Administrador</span>
                                                    break;
                                                case 2:

                                                    <span>Vendedor</span>
                                                    break;
                                                case 3:

                                                    <span>Bodeguero</span>
                                                    break;
                                                case 4:

                                                    <span>Cajero</span>
                                                    break;
                                                case 5:

                                                    <span>Cliente</span>
                                                    break;
                                                default:

                                                    <span>Usuario</span>
                                                    break;
                                            }
                                        </span>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a class="dropdown-item text-danger" asp-controller="Login" asp-action="Logout">
                                            <i class="bi bi-box-arrow-right"></i> Cerrar Sesión
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="d-flex flex-wrap justify-content-around align-items-center py-3 my-4 border-top">
        <div>
            &copy; 2025 - CashBlock - Sistema de Gestión de Ventas
        </div>
        <div>
            <a asp-controller="Home" asp-action="Index"><img src="../img/Mesa de trabajo 8.png" alt="" width="110" height="60"></a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>